MOCK_PLACES = [
    {
        "name": "Bar Irlanda Tucuman",
        "address": "Catamarca 380",
        "city": "San Miguel de Tucuman",
        "contact": None,
        "opening_hours": "Noche",
        "services": "Bar, tragos, comida",
        "source": "Mock dataset",
        "source_url": "mock://bares-tucuman",
    },
    {
        "name": "Irlanda Bar",
        "address": "Catamarca 380",
        "city": "San Miguel de Tucuman",
        "contact": None,
        "opening_hours": "Noche",
        "services": "Bar y comida",
        "source": "Mock dataset",
        "source_url": "mock://bares-tucuman",
    },
    {
        "name": "Cafe Martinez Tucuman",
        "address": "25 de Mayo 487",
        "city": "San Miguel de Tucuman",
        "contact": None,
        "opening_hours": "Manana y tarde",
        "services": "Cafe, pasteleria",
        "source": "Mock dataset",
        "source_url": "mock://bares-tucuman",
    },
    {
        "name": "La Pizzada",
        "address": "Munecas 555",
        "city": "San Miguel de Tucuman",
        "contact": None,
        "opening_hours": "Mediodia y noche",
        "services": "Pizzeria, restaurante",
        "source": "Mock dataset",
        "source_url": "mock://bares-tucuman",
    },
]
